feat(Admin-logs): AdminLog Model
metabrainz/bookbrainz-data-js pull request #306
Opened 2023-06-24 16:38 UTC by the-good-boy

Created a corresponding model for ``bookbrainz.admin_log`` table.

2023-06-26 14:36 UTC, MonkeyDo requested changes
Looks pretty good, some small details below.

We might have a need for an actionType (or "adminActionType"?) that would return `this.belongsTo('AdminActionType', 'action_type')`
See an example on some other type here: https://github.com/metabrainz/bookbrainz-data-js/blob/fbd1696538da28dfcf3997d08898275aaa3079cf/src/models/editor.js#L53-L55
And the EditorType model itself: https://github.com/metabrainz/bookbrainz-data-js/blob/fbd1696538da28dfcf3997d08898275aaa3079cf/src/models/editorType.js

2023-06-26 14:36 UTC, MonkeyDo commented on src/models/adminLog.js
> +		adminId() {
This should probably be `admin` if it returns an Editor model rather than just the ID

2023-06-26 14:36 UTC, MonkeyDo commented on src/models/adminLog.js
> +		tagetUserId() {
Same here, I think this should probably be `targetUser`

2023-06-26 15:12 UTC, the-good-boy commented
> We might have a need for an actionType (or "adminActionType"?) that would return `this.belongsTo('AdminActionType', 'action_type')` See an example on some other type here:


I dont think we'll need an actionType here. The reason being that in the case of an Editor, the type points to a TABLE, but here action_type points to a TYPE. 
Some other examples of similar models are `external_service_oauth_type` in the [ExternalServiceOauth Model](https://github.com/metabrainz/bookbrainz-data-js/blob/fbd1696538da28dfcf3997d08898275aaa3079cf/src/models/externalServiceOauth.js), and `entity_type` in the [Entity Model](https://github.com/metabrainz/bookbrainz-data-js/blob/fbd1696538da28dfcf3997d08898275aaa3079cf/src/models/entity.js). What do you think?

2023-06-27 12:43 UTC, MonkeyDo commented
> I dont think we'll need an actionType here. The reason being that in the case of an Editor, the type points to a TABLE, but here action_type points to a TYPE. Some other examples of similar models are `external_service_oauth_type` in the [ExternalServiceOauth Model](https://github.com/metabrainz/bookbrainz-data-js/blob/fbd1696538da28dfcf3997d08898275aaa3079cf/src/models/externalServiceOauth.js), and `entity_type` in the [Entity Model](https://github.com/metabrainz/bookbrainz-data-js/blob/fbd1696538da28dfcf3997d08898275aaa3079cf/src/models/entity.js). What do you think?

Yeah, that makes sense. Let's leave it as is then, and if the need arises for us to do any management of the TYPE (I can't remember how the bookshelf ORM returns SQL types) then we can look at it again.

2023-06-27 12:43 UTC, MonkeyDo approved these changes
Good to go ! :rocket:

2023-06-27 12:43 UTC, merged